version: 2
updates:
- package-ecosystem: npm
  directory: "/web-ui"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@fortawesome/fontawesome-free"
    versions:
    - 5.15.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: ress
    versions:
    - 3.0.0
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.lettuce:lettuce-core
    versions:
    - 6.0.2.RELEASE
    - 6.0.3.RELEASE
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - Hoxton.SR10
    - Hoxton.SR9
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.2
  - dependency-name: org.junit:junit-bom
    versions:
    - 5.7.0
