spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_demo_development?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
doma:
  dialect: mysql