spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_demo_development?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: gmailaddress
    password: gmailpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
doma:
  dialect: mysql