spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_demo_development?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  redis:
    url: redis://localhost:6379/0
  mail:
    host: smtp.gmail.com
    port: 587
    username: gmailaddress
    password: gmailpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

doma:
  dialect: mysql
  naming: snake_lower_case
cloud:
  aws:
    credentials:
      access-key: minio_access_key
      secret-key: minio_secret_key
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
storage:
  url: http://localhost:9000
